// Auto-generated by Supabase MCP. Do not edit manually.
// Regenerate with: mcp_supabase_generate_typescript_types
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      auth_audit_log: {
        Row: {
          created_at: string
          email_hash: string
          event_type: string
          id: number
          ip_hash: string | null
          user_agent: string | null
        }
        Insert: {
          created_at?: string
          email_hash: string
          event_type: string
          id?: number
          ip_hash?: string | null
          user_agent?: string | null
        }
        Update: {
          created_at?: string
          email_hash?: string
          event_type?: string
          id?: number
          ip_hash?: string | null
          user_agent?: string | null
        }
        Relationships: []
      }
      folders: {
        Row: {
          created_at: string
          id: string
          name: string
          owner_id: string
          parent_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          owner_id: string
          parent_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          owner_id?: string
          parent_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      media: {
        Row: {
          content_hash: string | null
          created_at: string
          deleted_at: string | null
          duration_seconds: number | null
          folder_id: string | null
          height: number | null
          id: string
          kind: Database["public"]["Enums"]["media_kind"]
          mime_type: string
          original_filename: string
          owner_id: string
          size_bytes: number
          status: Database["public"]["Enums"]["media_status"]
          storage_path: string
          thumbnail_path: string | null
          updated_at: string
          width: number | null
        }
        Insert: {
          content_hash?: string | null
          created_at?: string
          deleted_at?: string | null
          duration_seconds?: number | null
          folder_id?: string | null
          height?: number | null
          id?: string
          kind?: Database["public"]["Enums"]["media_kind"]
          mime_type: string
          original_filename: string
          owner_id: string
          size_bytes?: number
          status?: Database["public"]["Enums"]["media_status"]
          storage_path: string
          thumbnail_path?: string | null
          updated_at?: string
          width?: number | null
        }
        Update: {
          content_hash?: string | null
          created_at?: string
          deleted_at?: string | null
          duration_seconds?: number | null
          folder_id?: string | null
          height?: number | null
          id?: string
          kind?: Database["public"]["Enums"]["media_kind"]
          mime_type?: string
          original_filename?: string
          owner_id?: string
          size_bytes?: number
          status?: Database["public"]["Enums"]["media_status"]
          storage_path?: string
          thumbnail_path?: string | null
          updated_at?: string
          width?: number | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          full_name: string | null
          id: string
          updated_at: string
          username: string | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          full_name?: string | null
          id: string
          updated_at?: string
          username?: string | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          full_name?: string | null
          id?: string
          updated_at?: string
          username?: string | null
        }
        Relationships: []
      }
      rate_limit_buckets: {
        Row: {
          blocked_until: string | null
          bucket_key: string
          hit_count: number
          window_started_at: string
        }
        Insert: {
          blocked_until?: string | null
          bucket_key: string
          hit_count?: number
          window_started_at?: string
        }
        Update: {
          blocked_until?: string | null
          bucket_key?: string
          hit_count?: number
          window_started_at?: string
        }
        Relationships: []
      }
      share_link_views: {
        Row: {
          id: number
          origin: string | null
          outcome: string
          share_link_id: string
          viewed_at: string
          viewer_ip_hash: string | null
          viewer_user_agent: string | null
        }
        Insert: {
          id?: number
          origin?: string | null
          outcome: string
          share_link_id: string
          viewed_at?: string
          viewer_ip_hash?: string | null
          viewer_user_agent?: string | null
        }
        Update: {
          id?: number
          origin?: string | null
          outcome?: string
          share_link_id?: string
          viewed_at?: string
          viewer_ip_hash?: string | null
          viewer_user_agent?: string | null
        }
        Relationships: []
      }
      share_links: {
        Row: {
          allow_download: boolean
          allow_embed: boolean
          allowed_origins: string | null
          created_at: string
          expires_at: string | null
          id: string
          last_viewed_at: string | null
          max_views: number | null
          media_id: string
          owner_id: string
          password_hash: string | null
          revoked_at: string | null
          token_hash: string
          updated_at: string
          view_count: number
        }
        Insert: {
          allow_download?: boolean
          allow_embed?: boolean
          allowed_origins?: string | null
          created_at?: string
          expires_at?: string | null
          id?: string
          last_viewed_at?: string | null
          max_views?: number | null
          media_id: string
          owner_id: string
          password_hash?: string | null
          revoked_at?: string | null
          token_hash: string
          updated_at?: string
          view_count?: number
        }
        Update: {
          allow_download?: boolean
          allow_embed?: boolean
          allowed_origins?: string | null
          created_at?: string
          expires_at?: string | null
          id?: string
          last_viewed_at?: string | null
          max_views?: number | null
          media_id?: string
          owner_id?: string
          password_hash?: string | null
          revoked_at?: string | null
          token_hash?: string
          updated_at?: string
          view_count?: number
        }
        Relationships: []
      }
      user_preferences: {
        Row: {
          created_at: string
          notify_product_updates: boolean
          notify_security: boolean
          notify_share_activity: boolean
          notify_storage_warnings: boolean
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          notify_product_updates?: boolean
          notify_security?: boolean
          notify_share_activity?: boolean
          notify_storage_warnings?: boolean
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          notify_product_updates?: boolean
          notify_security?: boolean
          notify_share_activity?: boolean
          notify_storage_warnings?: boolean
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      check_brute_force: {
        Args: {
          p_email: string
          p_max_failures?: number
          p_window_minutes?: number
        }
        Returns: boolean
      }
      consume_rate_limit: {
        Args: {
          p_block_seconds?: number
          p_bucket_key: string
          p_max_hits: number
          p_window_seconds: number
        }
        Returns: boolean
      }
      get_user_storage_usage: {
        Args: never
        Returns: {
          file_count: number
          image_count: number
          used_bytes: number
          video_count: number
        }[]
      }
      hash_share_password: { Args: { p_password: string }; Returns: string }
      hash_token: { Args: { input: string }; Returns: string }
      record_auth_attempt: {
        Args: { p_email: string; p_event_type: string; p_user_agent?: string }
        Returns: undefined
      }
      resolve_share_link: {
        Args: {
          p_ip_hash: string
          p_origin: string
          p_password: string
          p_token_hash: string
          p_user_agent: string
        }
        Returns: {
          allow_download: boolean
          allow_embed: boolean
          duration_seconds: number
          height: number
          kind: Database["public"]["Enums"]["media_kind"]
          link_id: string
          media_id: string
          mime_type: string
          original_filename: string
          outcome: string
          size_bytes: number
          storage_path: string
          thumbnail_path: string
          width: number
        }[]
      }
      resolve_share_public: {
        Args: {
          p_token_hash: string
          p_password?: string | null
          p_origin?: string | null
          p_ip_hash?: string | null
          p_user_agent?: string | null
        }
        Returns: Json
      }
      trash_media: {
        Args: { p_media_ids: string[] }
        Returns: number
      }
      restore_media: {
        Args: { p_media_ids: string[] }
        Returns: number
      }
      permanently_delete_media: {
        Args: { p_media_ids: string[] }
        Returns: number
      }
    }
    Enums: {
      media_kind: "image" | "video" | "other"
      media_status: "uploading" | "processing" | "ready" | "failed"
    }
    CompositeTypes: { [_ in never]: never }
  }
}
